### ISSUE TITLE
Feature - Posibilidad de trabajar con multiples componentes y diferentes cotizaciones

### ISSUE THREAD

**Issue by ramiroandrescruz** [EzequielRamis/arsat#1]
Escenario:
Resultaria util poder contar con multiples componentes de grafico para visualizar multiples cotizaciones e historicos simultaneamente. 

Posible solucion:
Permitir el agregado de varios contenedores de graficos con distintas cotizaciones. cada uno de estos contenedores debe de persistir su configuracion de moneda en el tiempo via cookies o algo similar.  Tambien se puede utilizar un mismo grafico con distintos niveles de visualizacion

Ejemplos:
![dashboard-dark](https://user-images.githubusercontent.com/57991885/108070265-14433280-7043-11eb-85b0-6e3d2066e769.png)
![69681488-dashboard-ui-and-ux-kit-bar-chart-and-line-graph-designs-different-infographic-elements-dark-backgro](https://user-images.githubusercontent.com/57991885/108096916-43b46800-7060-11eb-8eb7-61ac45b3ff2a.jpg)

**Comment by EzequielRamis** [comment]
Bastante heavy el feature jaja, el codigo de front no lo tengo tan escalado para agregar algo parecido.
